// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMkovDUKHyie8FHhgwZcMHudlUCIcFJAs',
    appId: '1:946085838470:web:2ce76bd0d7cfbdf38f5b07',
    messagingSenderId: '946085838470',
    projectId: 'shoee-3c816',
    authDomain: 'shoee-3c816.firebaseapp.com',
    storageBucket: 'shoee-3c816.appspot.com',
    measurementId: 'G-ZK974EF43C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCblnQItvfbQ6eZ1lSKKns5C_c1Hax1JTo',
    appId: '1:946085838470:android:b6007afc341c9f828f5b07',
    messagingSenderId: '946085838470',
    projectId: 'shoee-3c816',
    storageBucket: 'shoee-3c816.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZbb9Dn0aRosxEcRKHMwgEgG0jLjKTqhQ',
    appId: '1:946085838470:ios:ab10e1b2cc2e144f8f5b07',
    messagingSenderId: '946085838470',
    projectId: 'shoee-3c816',
    storageBucket: 'shoee-3c816.appspot.com',
    iosClientId: '946085838470-4mcdf1r1qjo04tt0ckcj07n15jet6luk.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZbb9Dn0aRosxEcRKHMwgEgG0jLjKTqhQ',
    appId: '1:946085838470:ios:ab10e1b2cc2e144f8f5b07',
    messagingSenderId: '946085838470',
    projectId: 'shoee-3c816',
    storageBucket: 'shoee-3c816.appspot.com',
    iosClientId: '946085838470-4mcdf1r1qjo04tt0ckcj07n15jet6luk.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoee',
  );
}
